// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef_core.Data;

#nullable disable

namespace apiCrud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929192928_HorasNoTrabajadas")]
    partial class HorasNoTrabajadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ef_core.Data.BiometricoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsLlegadaAlmuerzo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsSalida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsSalidaAlmuerzo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BiometricoData");
                });

            modelBuilder.Entity("ef_core.Data.SeatData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraRegresoAlmuerzo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraSalidaAlmuerzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPermiso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeatData");
                });
#pragma warning restore 612, 618
        }
    }
}
